# Generated by Django 3.1.3 on 2021-01-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('dateJoined', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('role', models.ManyToManyField(to='ards_site.Role')),
                ('teamsPlayedFor', models.ManyToManyField(to='ards_site.Team')),
                ('type', models.ManyToManyField(to='ards_site.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Bowling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('overs', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('wickets', models.IntegerField(blank=True, null=True)),
                ('extras', models.CharField(default='', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ards_site.member')),
                ('opponent', models.ManyToManyField(to='ards_site.Opponent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ards_site.team')),
            ],
        ),
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('sixes', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ards_site.member')),
                ('opponent', models.ManyToManyField(to='ards_site.Opponent')),
                ('out', models.ManyToManyField(to='ards_site.Wicket')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ards_site.team')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ards_site.member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ards_site.team')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ards_site.cup')),
            ],
        ),
    ]
